services:
  api:
    build:
      dockerfile: ./Dockerfile
    image: libertai-api
    container_name: libertai-api
    restart: unless-stopped
    command: poetry run uvicorn src.server:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 30 --timeout-graceful-shutdown 600 --loop uvloop --limit-concurrency 500
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
